wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1671285145.360263
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      2:
      - 1
      - 41
      - 50
      - 55
      3:
      - 13
      - 23
      4: 3.9.12
      5: 0.13.5
      8:
      - 3
      - 5
